### ISSUE TITLE
Copyright/Attribution

### ISSUE THREAD

**Issue by drudge** [hckdotng/n8n-nodes-puppeteer-extended#1]
Hi there!

This looks like a cool addition to the Puppeteer node that I wrote. Is there a reason that the copyright/attribution was removed from the license?

From the license:
>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

**Comment by hckdotng** [comment]
I thought it was only necessary to keep the mention of the MIT license, I modify that (no intention not to credit you, the README refers to the original node), sorry.

**Comment by drudge** [comment]
No worries! Your changes to the node look pretty cool. Let me know if you'd like to collaborate in the future!

**Comment by hckdotng** [comment]
I intent to work on the Discord node, if you're interested I'll be glad to collaborate with you on this :)
